name: CI

on:
  schedule:
    - cron: '30 2 * * *'  # Run once per day

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:  # NOTE: Must also allow github actions to create and apprpve pull requests from repo settings
  contents: write
  pull-requests: write

jobs:
  unciv-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      
      - name: oxipng image compression # This needs to be before the Unciv run since that packs images
        shell: bash
        run: | 
          set -euo pipefail
          oxipng_url=$(curl -L -s https://api.github.com/repos/oxipng/oxipng/releases/latest | grep -o "http.*x86_64-unknown-linux-gnu.tar.gz")
          wget -O oxipng.tar.gz $oxipng_url
          tar -xvzf oxipng.tar.gz
          rm oxipng.tar.gz
          
          mv oxipng-*-x86_64-unknown-linux-gnu/oxipng .
          rm -fr oxipng-*-x86_64-unknown-linux-gnu/
          find Images* -type f -regex ".*png" | xargs -d '\n' ./oxipng -o max --strip all --alpha -v
          rm -rf oxipng

      - uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Autoupdate
        continue-on-error: true  # We want to autoupdate even if there are errors
        shell: bash
        run: |
          set -euo pipefail
          unciv_url=$(curl -s https://api.github.com/repos/yairm210/unciv/releases/latest | grep -o "http.*Unciv.jar")
          wget -q -O Unciv.jar $unciv_url
          java -jar Unciv.jar mod-ci

      - name: Remove Unciv executable
        run: rm Unciv.jar

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          title: '[chore]: ci autoupdate'
          body: '[chore]: optimized images and updated `game.atlas`'
          assignees: ['right-ward']
